# 実際には Node を使うが、Objective-C を指定することで OS X 環境で動かすようにする
language: objective-c
cache:
  directories:
    - node_modules
env:
  # Node はコマンドを個別に実行してインストールするため、ここでバージョンを指定する
  - NODE_VERSION="4.6.0"
before_install:
  # nvm をインストールする。Travis の OS X 環境には nvm はデフォルトで入っていない
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  # 指定バージョンの Node をインストールする
  - nvm install $NODE_VERSION
  # 指定バージョンの Node を有効にする
  - nvm use --delete-prefix $NODE_VERSION
  - node --version
install:
  - npm install
script:
  - npm test
before_deploy:
  # brew は最新状態にする
  - brew update
  # Windows環境へのビルドのために Wine は必須
  - brew install wine --without-x11
  - wine --version
  - brew install mono
  # Windowsインストーラ作成のために makensis は必須
  - brew install makensis
  # ビルド + インストーラ作成 + zip化 までを各プラットフォームに対して行う
  - npm run release
  - ls -l dist
deploy:
  provider: releases
  api_key:
    secure: PuBLO7cGoea5YPMENVYJMJYyp101PgIn1jC0+H1stJNpnMDDPaDxL1zGoz5whHIgAUELGWEFp13NDLlB06UIbcwH5uK7lQJEyIuaYeNsAI5JvmkeCh+WJPCd0tX1zeTczJ4EKMfDchaSUgyFS3LygiPTYINJJjAaeCvdE7EznJY8AlORDHe2zyiO/jhsBuJrh0lKrRgYbVPkVvjegQFkdOAFnSfhpAXtNj+Yuf4sSiKpPlETSw8JWDJhOP3w/QPVEwQl3I75scals2pFBtc5xqoBVvNFk5WY9QjQR9KHCNrP6MN0T2ftzx1UTBGFetV0dyCfCYOtvi0kuxLzdELrqCIldJJGwQx2Pw1NF00GNUq/0JznvBIsZKsyFxGox4fjcdbumq171ThTBXS5RimnSdOZa6/wWbkYJfFPwOsV1QgSWoU51o9EJolzaV79hoR1HPizLPHfOudwD0/jouh1gP5uIA8DpsQcYPcuYtRZkWv7ajwrAwfp60RBrYFX8EsbXY6bcFt6a6MZvu3dNXrYAxva0W2pO/gzXmyWkdID6LJDRY3ozhtG5VCdW9CM6WKf28bOyVGQ9Afw4dM9CW1yzs56QyscT9IDzvdGTLSl9KlBhL4zCd0aNqJKXNqbmj3Y+96G0IhWbi9Uno22ucTrmrvLsQKMBK2lu5Bew0a+xCo=
  file:
    - dist/win-ia32/gauth-electron Setup 1.0.1-ia32.exe
    - dist/mac/gauth-electron-1.0.1.dmg
  skip_cleanup: true
  on:
    repo: sadapon2008/gauth-electron
    tags: true
    all_branches: true
